# Generated by Django 6.0 on 2026-01-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_otp_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
