# Generated by Django 6.0 on 2026-01-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(default=123456, max_length=11),
            preserve_default=False,
        ),
    ]
